# Generated by Django 6.0.3 on 2026-03-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mob', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=100, unique=True)),
                ('college', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experiance', models.IntegerField()),
            ],
        ),
    ]
