# Generated by Django 6.0.3 on 2026-03-26 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mob', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('usn', models.CharField(max_length=10, unique=True)),
                ('college', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('sem', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
            ],
        ),
    ]
